package com.apps.ecommerce.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import lombok.extern.slf4j.Slf4j;

@Service
@Slf4j
public class MailService {

    private final JavaMailSender mailSender;
    private final String from;

    /**
     * Written out rather than generated by @RequiredArgsConstructor: Lombok does
     * not copy field annotations onto constructor parameters, so a @Value on the
     * field would be ignored and `from` would stay null — every message going out
     * with no From header. Mailpit accepts that; a real relay rejects it.
     */
    public MailService(JavaMailSender mailSender, @Value("${app.mail.from}") String from) {
        this.mailSender = mailSender;
        this.from = from;
    }

    public void send(String to, String subject, String text) {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom(from);
        message.setTo(to);
        message.setSubject(subject);
        message.setText(text);
        mailSender.send(message);
        log.info("Mail sent to {}", to);
    }

}
