package com.apps.ecommerce.service;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import lombok.extern.slf4j.Slf4j;

/**
 * Plain SMTP. Good for local development against Mailpit, where there are no
 * credentials and no TLS. Do not expect this to work on Render: its instances
 * cannot open outbound connections on 25, 465 or 587, and the attempt does not
 * fail fast - it hangs until the socket timeout.
 */
@Service
@ConditionalOnProperty(name = "app.mail.provider", havingValue = "smtp", matchIfMissing = true)
@Slf4j
public class SmtpMailService implements MailService {

    private final JavaMailSender mailSender;
    private final String from;

    /**
     * Written out rather than generated by @RequiredArgsConstructor: Lombok does
     * not copy field annotations onto constructor parameters, so a @Value on the
     * field would be ignored and `from` would stay null.
     */
    public SmtpMailService(JavaMailSender mailSender, @Value("${app.mail.from}") String from) {
        this.mailSender = mailSender;
        this.from = from;
    }

    @Override
    public void send(String to, String subject, String text) {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom(from);
        message.setTo(to);
        message.setSubject(subject);
        message.setText(text);
        mailSender.send(message);
        log.info("Mail sent to {} over SMTP", to);
    }
}
